SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE SCHEMA IF NOT EXISTS `cmpe207` DEFAULT CHARACTER SET utf8mb4 ;
USE `cmpe207` ;

-- -----------------------------------------------------
-- Table `cmpe207`.`Files`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `cmpe207`.`Files` (
  `idFiles` INT(11) NOT NULL AUTO_INCREMENT ,
  `file_name` VARCHAR(45) NOT NULL ,
  `user_name` VARCHAR(45) NULL DEFAULT NULL ,
  `file_size` INT(11) NULL DEFAULT NULL ,
  `file_type` VARCHAR(45) NULL DEFAULT NULL ,
  `new_name` VARCHAR(80) NULL DEFAULT NULL ,
  `url` VARCHAR(200) NULL DEFAULT NULL ,
  PRIMARY KEY (`idFiles`) )
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8mb4;

USE `cmpe207` ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
